twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'form/custom_errors.html.twig'
    globals:
        app_version: '%env(APP_VERSION)%'
when@test:
    twig:
        strict_variables: true
